# Use a suitable base image for Windows
FROM openjdk:11-windowsservercore

# Set the working directory in the container
WORKDIR /app

# Copy the packaged jar file into the container
COPY target/*.jar app.jar

# Define the command to run the application when the container starts
CMD ["java", "-jar", "app.jar"]
